##################################################
######### Joint Group Velocity Controller ########
##################################################
VelocityControllers_JointGroupVelocityController:
  type: velocity_controllers/JointGroupVelocityController
  joints: 
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7

  gains:
    joint_1: {p: 10, i: 0, d: 0}
    joint_2: {p: 10, i: 0, d: 0}
    joint_3: {p: 10, i: 0, d: 0}
    joint_4: {p: 10, i: 0, d: 0}
    joint_5: {p: 10, i: 0, d: 0}
    joint_6: {p: 10, i: 0, d: 0}
    joint_7: {p: 10, i: 0, d: 0}

robot:
  pos_corr_gain: 0 # parameter in RAPID that needs to be set to zero to accept velocity commands alone
