##################################################
######### Joint Group Velocity Controller ########
##################################################
VelocityControllers_JointGroupVelocityController:
  type: velocity_controllers/JointGroupVelocityController
  joints: 
    - J1
    - J2
    - J3
    - J4
    - J5
    - J6
  publish_rate: 100

  gains:
    J1: {p: 0.0, i: 0, d: 0}
    J2: {p: 0.0, i: 0, d: 0}
    J3: {p: 0.0, i: 0, d: 0}
    J4: {p: 0.0, i: 0, d: 0}
    J5: {p: 0.0, i: 0, d: 0}
    J6: {p: 0.0, i: 0, d: 0}


robot:
  pos_corr_gain: 0 # parameter in RAPID that needs to be set to zero to accept velocity commands alone
